import {type Models} from "react-native-appwrite";

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types -l ts D:\alkabir\alkabir_backend`.

export enum Type {
  BOOKING = "Booking",
  REMINDER = "Reminder",
  STATUS_UPDATE = "StatusUpdate",
  PROMOTION = "Promotion",
}

export enum NotificationType {
  APP = "app",
  SMS = "sms",
  EMAIL = "email",
}

export type Profiles = Models.Document & {};

export type Services = Models.Document & {};

export type Categories = Models.Document & {
  name: string;
  slug: string;
  description: string;
  imageUrl: string;
  isActive: boolean;
};

export type Bookings = Models.Document & {};

export type Blogs = Models.Document & {};

export type Banners = Models.Document & {};

export type Notifications = Models.Document & {
  userId: string;
  title: string;
  message: string;
  type: Type;
  isRead: boolean;
  notificationType: NotificationType;
};
